apiVersion: v1
kind: Service
metadata:
  name: comentarios-api-service
spec:
  selector:
    app: comentarios-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
