apiVersion: apps/v1
kind: Deployment
metadata:
  name: comentarios-api
  namespace: api-comments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comentarios-api
  template:
    metadata:
      labels:
        app: comentarios-api
    spec:
      containers:
      - name: comentarios-api
        image: floresss/challenge:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
